[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bsdiff = "0.1.6"
miniz_oxide = "0.7.1"
rand = "0.8.3"
