name: Tests

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --release --verbose
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --release --verbose
